### ISSUE TITLE
Package wants to overwrite my Web.config

### ISSUE THREAD

**Issue by lcichanowicz** [redmorello/Our.Umbraco.DocTypePicker#1]
Hi, @redmorello.  I just installed the DocTypePicker package via Visual Studio 2019's NuGet Package Manager GUI.  (My site is Umbraco 7.14.0.)  It prompted me to overwrite my site's Web.config.  I am using source control, so I allowed the overwrite, so I could diff it and see if there was anything in there I needed.  I do not see anything specific to the DocTypePicker package in the overwritten Web.config.  Have I missed something?  If not, can your remove the Web.config from the installation?

**Comment by redmorello** [comment]
Hi @lcichanowicz , if I get time, I'll try and take a look today.

**Comment by redmorello** [comment]
Package has been updated.
