### ISSUE TITLE
Backoffice error when using data type

### ISSUE THREAD

**Issue by lcichanowicz** [redmorello/Our.Umbraco.DocTypePicker#2]
When I add a property to a doc type that uses the DocTypePicker, I get an error after selecting the property editor.

![image](https://user-images.githubusercontent.com/4871064/66222170-88737500-e69e-11e9-96c9-584d606116e7.png)

**Comment by redmorello** [comment]
Hi @lcichanowicz, can you confirm that you have the Our.Umbraco.DocTypePicker.dll in the bin folder please?

You should also have the following files in the App_Plugins/OurUmbracoDocTypePicker folder:

<img width="208" alt="Screenshot 2019-10-07 at 11 14 17" src="https://user-images.githubusercontent.com/7428078/66303819-c7e6cf00-e8f3-11e9-9165-d7f0ad665e8e.png">

I've tried adding the package 2.0.1 to an existing Umbraco site, and didn't see the error message.

**Comment by lcichanowicz** [comment]
Hi, @redmorello.  I do not have the DLL in the bin folder.  I do have the files you listed in the App_Plugins/OurUmbracoDocTypePicker folder.  I even tried uninstalling and reinstalling the package, but nothing is added to the bin folder.

![image](https://user-images.githubusercontent.com/4871064/66320988-d631ec80-e8ed-11e9-9bb6-65a77c254aed.png)

**Comment by redmorello** [comment]
@lcichanowicz hmm, not sure what to suggest. The DLL is in the nuget package:

<img width="376" alt="Screenshot 2019-10-07 at 16 36 08" src="https://user-images.githubusercontent.com/7428078/66326363-bbc53680-e920-11e9-8b2f-ea10973ae91b.png">

**Comment by lcichanowicz** [comment]
My application had **Target framework** set to 4.7.0.  I changed my target framework to 4.7.2, uninstalled your NuGet package and reinstalled.  Now the DLL is in my bin folder.

**Comment by lcichanowicz** [comment]
@redmorello, perhaps you could support multi versions of the .NET Framework.

https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks

**Comment by redmorello** [comment]
@lcichanowicz Umbraco 8 has a dependency on 4.7.2, hence why this package also uses this version.

**Comment by lcichanowicz** [comment]
UGH!  Yes, exactly.  I just found that your NuGet package tried to upgrade my Umbraco 7 site to 8.

![image](https://user-images.githubusercontent.com/4871064/66402391-c203f300-e9b2-11e9-833e-39e67a04f97e.png)

You really should have a declared dependency on Umbraco 8 in your NuGet package.
