### ISSUE TITLE
dotnet build fails to copy content because of incorrect path

### ISSUE THREAD

**Issue by wileyveteran** [redmorello/Our.Umbraco.DocTypePicker#9]
When running a dotnet build, the location in the targets file is given as 
```
        <OurUmbracoDocTypePickerContentFilesPath>$(MSBuildThisFileDirectory)..\App_Plugins\OurUmbracoDocTypePicker\**\*.*</OurUmbracoDocTypePickerContentFilesPath>

```
However, the files are located in \content\App_Plugins ....  which results in no files copied

`Copying Our.Umbraco.DocTypePicker files: C:\Users\username\.nuget\packages\our.umbraco.doctypepicker\3.0.0\buildTransitive\..\App_Plugins\OurUmbracoDocTypePicker\**\*.* - #0 files`

**Comment by redmorello** [comment]
@wileyveteran what happens if you use the Pack menu option when right clicking on the Our.Umbraco.DocTypePicker project in Visual Studio?

**Comment by wileyveteran** [comment]
Sorry, I wasn't clear. I am not talking about building this package, I mean once I install the nuget package into my Umbraco v9 and do a dotnet build on my solution it does not install the files in the App_Plugins folder because the targets file is not pointing to the correct location in the published nuget package.

**Comment by redmorello** [comment]
Ah ok, I’ll take a look, thanks for raising the issue 👍

**Comment by redmorello** [comment]
@wileyveteran this issue should now be fixed. v3.0.1 pushed to nuget.
